name=AMIS MPPT Solar Charger Driver
version=1.0.0
author=locker98
maintainer=locker98
sentence=A library for compunicating with AIMS Solar charger.
paragraph=A library for compunicating with AIMS Solar charger.
url=https://github.com/thelocker98/AIMS-Solar-Charger.git
architectures=*
includes=MPPTController.h
