name=AMIS MPPT Solar Charger Driver
version=1.1.15
author=locker98
maintainer=locker98
sentence=Required for all Adafruit Unified Sensor based libraries.
paragraph=A unified sensor abstraction layer used by many Adafruit sensor libraries.
category=Sensors
url=https://github.com/thelocker98/
architectures=*
includes=MPPTController.h
